run:
  timeout: 5m
  go: "1.24"

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/haruotsu/ezpw
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 100
    statements: 50
  godot:
    scope: toplevel
  gofumpt:
    extra-rules: true
  gosec:
    severity: low
    confidence: medium

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - depguard
    - exhaustive
    - gochecknoglobals
    - godox
    - err113
    - nestif
    - prealloc
    - testpackage
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - dupl
    - path: cmd/
      linters:
        - gochecknoinits
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck